Cart/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import cart

urlpatterns = [
    path('', cart, name="cart"),
]

Grocery/urls.py
from django.contrib import admin
from . import views
from django.urls import  path

urlpatterns = [
    path('', views.getgrocery, name = 'grocery'),
    path('cart/<str:id>/', views.gocart, name='cart'),
]

fastfood/urls.py
from django.contrib import admin
from . import views
from django.urls import  path
# # from django.contrib.staticfiles.urls import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# # from ..tk1 import settings
 
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('', views.getfastfood, name = 'fastfood'),
    path('cart/<str:id>/', views.tocart, name='cart'),
    path('search/', views.search, name='search'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home , name='home'),
]

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.recipes, name='recipes'),
    path('deskripsi/<str:id>/', views.deskripsi, name='deskripsi'),
    path('tambah/', views.tambah, name='tambah'),
]

tk1/urls.py
from tk1.settings import MEDIA_ROOT
from django.contrib import admin
from django.urls import include, path
from main import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing_page, name='landing_page'),
    path('home/', include('main.urls')),
    path('recipes/', include('recipes.urls')),
    path('grocery/', include('Grocery.urls')),
    path('fastfood/', include('fastfood.urls')),
    path('recipes/', include('recipes.urls')),
    path('cart/', include('Cart.urls'))  
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cart/models.py
from django.db import models

# Create your models here.
class Cart(models.Model):
    nama_cart = models.CharField(max_length = 256)
    location_cart = models.CharField(max_length = 1000, null = True)
    harga_cart = models.PositiveIntegerField()
    foto_cart = models.ImageField(null=True, blank=True)
    porsi = models.IntegerField()

    
    def __str__(self):
        return self.name

Grocery/models.py
from django.db import models
from cloudinary.models import CloudinaryField

# Create your models here.
class grocery(models.Model):
    nama = models.CharField(max_length = 256)
    porsi = models.IntegerField()
    location = models.CharField(max_length = 1000)
    harga = models.PositiveIntegerField()
    foto = CloudinaryField(null=True, blank=True)

    def class_name(self):
        return "Grocery"

fastfood/models.py
from django.db import models
from cloudinary.models import CloudinaryField

# Create your models here.
class fastfood(models.Model):
    nama = models.CharField(max_length = 256)
    porsi = models.IntegerField()
    location = models.CharField(max_length = 1000)
    harga = models.PositiveIntegerField()

    def class_name(self):
        return "fastfood"

class fastfood2(models.Model):
    nama = models.CharField(max_length = 256)
    porsi = models.IntegerField()
    location = models.CharField(max_length = 1000)
    harga = models.PositiveIntegerField()
    foto = CloudinaryField(null=True, blank=True)

    def class_name(self):
        return "Fast Food"

main/models.py
from django.db import models

# Create your models here.

class Pelanggan(models.Model):
    name = models.CharField(max_length=50)

    def get_name(self):
        return self.name

recipes/models.py
import cloudinary
from django.db import models
from django.utils import timezone
from datetime import datetime, date
from cloudinary.models import CloudinaryField

class recipe(models.Model):
    nama = models.CharField(max_length=30)
    photo = CloudinaryField(null=True, blank=True)
    deskripsi = models.TextField()

Cart/forms.py
from django import forms
from .models import dataCekot


class formCekot(forms.Form):

    class Meta:
        model = dataCekot
        fields = ('__all__')

    attrs = {'class': 'form-control'}
    namaDepan = forms.CharField(widget=forms.TextInput(
        attrs=attrs), label='Nama Depan', max_length=100, required=True)
    namaBelakang = forms.CharField(widget=forms.TextInput(
        attrs=attrs), label='Nama Belakang', max_length=100, required=True)
    email = forms.CharField(widget=forms.Textarea(
        attrs=attrs), label='Email ',max_length=100, required=True)
    Alamat = forms.CharField(widget=forms.TextInput(
        attrs=attrs), label='Alamat', max_length=3000, required=True)

main/forms.py
from django import forms
from .models import Pelanggan

class Form_Nama(forms.ModelForm):
    class Meta:
        model = Pelanggan
        fields = ['name']

recipes/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import fields
from django.forms import widgets
from .models import *

class tambahkan(ModelForm):
    class Meta:
        model = recipe;
        fields = '__all__'
        widgets = {
            'nama' : forms.TextInput(attrs={'class': 'form-control'}),
            'photo' : forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'deskripsi' : forms.Textarea(attrs={'class': 'form-control'}),
        }

Cart/views.py
from django.shortcuts import render

# Create your views here.

def cart(request):
    return render(request, 'cart.html')

Grocery/views.py
from django.shortcuts import render
from .models import grocery
from cloudinary.forms import cl_init_js_callbacks

# Create your views here.
def getgrocery(request):
    result = grocery.objects.all()
    context = {'result':result}
    return render(request, 'grocery.html',context)

def gocart(request,id):
    desc = grocery.objects.get(id=id)
    context = {'desc':desc}
    return render(request, 'cart.html',context)

fastfood/views.py
from django.shortcuts import render
from .models import fastfood2, fastfood
from cloudinary.forms import cl_init_js_callbacks

# Create your views here.
def getfastfood(request):
    result = fastfood2.objects.all()
    context = {'result':result}
    return render(request, 'fastfood.html',context)

def tocart(request,id):
    desc = fastfood2.objects.get(id=id)
    context = {'desc':desc}
    return render(request, 'cart.html',context)

def search(request):
    if request.method =="POST" and request.POST.get("carinama") !=None:
        search = request.POST.get("carinama")
        produk = fastfood2.objects.filter(nama__contains=search)
        response = {
            'produk' : produk,
        }
        return render(request,'search_fastfood.html', response)
    else:
        produk = fastfood2.objects.all()
        response = {
            'produk' : produk,
        }
        return render(request,'search_fastfood.html', response)

main/views.py
from main.models import Pelanggan
from Grocery.models import grocery
from recipes.models import recipe
from fastfood.models import fastfood2
from django.forms.forms import Form
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.utils import http
from .forms import Form_Nama


def home(request):
    form = Form_Nama(request.POST or None)
    if form.is_valid():
        form.save()
    nama_pelanggan = Pelanggan.objects.last()
    recipes = recipe.objects.reverse()[:4]
    groceries = grocery.objects.reverse()[:4]
    fastfoods = fastfood2.objects.reverse()[:4]
    context = {
        'name' : nama_pelanggan.get_name,
        'recipes' : recipes,
        'groceries' : groceries,
        'fastfoods' : fastfoods
    }
    return render(request, 'main/home.html', context)

def landing_page(request):
    form = Form_Nama(request.POST or None)
    context = {
        'form_input_user' : form,
    }
    return render(request, "landingpage.html", context)

recipes/views.py
from .forms import tambahkan
from django.shortcuts import redirect, render
from .models import recipe
from cloudinary.forms import cl_init_js_callbacks

def recipes(request):
    result = recipe.objects.all()
    context = {'result':result}
    return render(request, 'main/recipes.html',context)

def deskripsi(request,id):
    desc = recipe.objects.get(id=id)
    context = {'desc':desc}
    return render(request, 'main/deskripsi.html',context)

def tambah(request):
    form = tambahkan()
    context = {'form':form}
    if request.method == 'POST':
        form = tambahkan(request.POST, request.FILES)
        form_class = tambahkan
        if form.is_valid():
            form.save()
            return redirect('/recipes')
    return render(request, 'main/tambah.html',context)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="/static/css/style.css" type="text/css">
{% endblock %}

{% block title %}
<title>Home</title>
{% endblock %}


{% block content %}
<div class="container-home d-flex flex-column justify-content-center">
  <div class="container p-2">
    <h1>Welcome, {{ name }}!</h1>
  </div>
  <div class="container p-2 home-intro">
    <div class="row align-items-center">
      <div class="col-sm" style="width: 80%; height: 78%;">
        <div class="container container-description">
          <p class="description-title">FAST AND HEALTHY, IMAGINE THAT!</p>
          <p class="description-text">Fresh House is an e-commerce platform that serves healthy recipes, fast food, and
            groceries to buy! We’re looking forward for your enthusiast!</p>
          <a href="{% url 'main:home'%}#about" class="btn btn-success">Get Started</a>
        </div>
      </div>
      <div class="col-sm" style="width: 80%; height: 78%;">
        <div class="logo"></div>
      </div>
    </div>
  </div>
  <br>
  <br>

  <h3 class="container">Recipes</h3>
  <div class="container d-flex flex-row justify-content-between home-recipe">
    {% for recipe in recipes %}
    <div class="card" style="width: 18rem">
      <div class="card-body text-center">
        <img src="{{recipe.photo.url}}" class="card-img-top" alt="photo not uploaded" style="height: 150px">
        <h5 class="card-title mt-3">{{recipe.nama}}</h5>
        <a href={%url 'recipes:deskripsi' recipe.id%} class="btn btn-success">See Recipe</a>
      </div>
    </div>
    {% endfor %}
  </div>
  <a href="/recipes/" class="btn btn-success container" style="width: 18rem;">View more Recipes</a>

  <h3 class="container">Groceries</h3>
  <div class="container d-flex flex-row justify-content-between home-grocery">
    {% for grocery in groceries %}
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <img src="{{grocery.foto.url}}" class="card-img-top" alt="photo not uploaded">
        <h5 class="card-title">{{grocery.nama}}</h5>
        <p>Porsi per sajian : {{grocery.porsi}} </p>
        <p>Lokasi Toko : {{grocery.location}} </p>
        <h5>Rp {{grocery.harga}} </h5>
        <a href="/grocery/cart/{{grocery.id}}/" class="btn btn-success">Add to Cart</a>
      </div>
    </div>
    {% endfor %}
  </div>
  <a href="/grocery/" class="btn btn-success container" style="width: 18rem;">View more Groceries</a>

  <br>
  <h3 class="container">Fast foods</h3>
  <div class="container d-flex flex-row justify-content-between recipe-fastfood">
    {% for fastfood in fastfoods %}
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <img src="{{fastfood.foto.url}}" class="card-img-top" alt="photo not uploaded">
        <h5 class="card-title">{{fastfood.nama}}</h5>
        <p>Porsi per sajian : {{fastfood.porsi}} </p>
        <p>Lokasi Toko : {{fastfood.location}} </p>
        <h5>Rp {{fastfood.harga}} </h5>
        <a href="/fastfood/cart/{{fastfood.id}}/" class="btn btn-success">Add to Cart</a>
      </div>
    </div>
    {% endfor %}
  </div>
  <a href="/fastfood/" class="btn btn-success container" style="width: 18rem;">View more Fast Foods</a>

  <div class="container d-flex flex-column justify-content-around home-about" id="about">
    <h1 class="p-2" style="text-align: center;">About</h1>
    <div class="row p-2">
      <div class="col-md">
        <img class="about-picture" src="/static/css/img/sehat.png">
      </div>
      <div class="col-md d-flex flex-column justify-content-center">
        <h2 class="p-2">Healthy and hygienic</h2>
        <p class="p-2">
          We provide a selection of recipes, food ingredients, and healthy intake to maintain your health, especially in
          the midst of this COVID-19 Pandemic
        </p>
      </div>
    </div>
    <div class="row p-2">
      <div class="col-md">
        <img class="about-picture" src="/static/css/img/dekat.png">
      </div>
      <div class="col-md d-flex flex-column justify-content-center">
        <h2 class="p-2">Close to you</h2>
        <p class="p-2">
          Just with one press, you can get the healthy intake you want right away</p>
      </div>
    </div>
    <div class="row p-2">
      <div class="col-md">
        <img class="about-picture" src="/static/css/img/beragam.jpg">
      </div>
      <div class="col-md d-flex flex-column justify-content-center">
        <h2 class="p-2">Diverse choices</h2>
        <p class="p-2">
          Feel free to choose a variety of recipes, ingredients, and, fast food here</p>
      </div>
    </div>
  </div>

  <div class="container d-flex flex-column justify-content-around home-contact" style="height: 300px" id="contact-us">
    <div class="p-2 contact-us-text">
      <h1 style="text-align: center;">Contact Us</h1>
    </div>
    <div class="p-2 contact-us-logo">
      <div class="d-flex justify-content-center">
        <a href="https://www.facebook.com/ahmad.harori.52">
          
          <img class="p-2" src="/static/css/img/facebook.png" style="width: 80px; height: 80px;">
        </a>
        <a href="https://www.instagram.com/ahmadharori/">
          <img class="p-2" src="/static/css/img/ig.png" style="width: 80px; height: 80px;">
        </a>
      </div>
    </div>
  </div>

</div>
{% endblock content %}

recipes/templates/main/deskripsi.html
{% extends 'base.html' %}
{%load static%}

{% block static %}
<link rel="stylesheet" href="/static/css/style.css">
{% endblock %}

{% block title %}  
<title>Recipe Description | Fresh House</title>
{% endblock %}

{% block content %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body class="container-grocery">
    <div class="text-center">
    <div class="card" style="margin-top: 50px; max-width: 75% ">
        <p class="text-left"> {{ desc.deskripsi |linebreaksbr }} </p> 
    </div>
    </div>
    <div class="text-center">
        <a href={%url 'recipes:recipes'%} class="btn btn-danger">Back</a>
    </div>
    <p></p>
</body>
{% endblock content %}

recipes/templates/main/recipes.html
{% extends 'base.html' %}
{%load static%}

{% block static %}
<link rel="stylesheet" href="/static/css/style.css">
{% endblock %}

{% block title %}  
<title>Recipes | Fresh House</title>
{% endblock %}

{% block content %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body class="container-grocery">
    {% for res in result %}
    <div class="card" style="width: 280px; height: 300px">
      <div class="card-body text-center">
        <img src="{{res.photo.url}}" class="card-img-top" alt="photo not uploaded" style="height: 150px">
        <h5 class="card-title mt-3">{{res.nama}}</h5>
        <a href={%url 'recipes:deskripsi' res.id%} class="btn btn-success">See Recipe</a>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="text-center">
    <a href={%url 'recipes:tambah'%} class="btn btn-success">Add Recipe</a>
  </div>
  <p></p>
</body>
{% endblock content %}

recipes/templates/main/tambah.html
{% extends 'base.html' %}
{%load static%}

{% block static %}
<link rel="stylesheet" href="/static/css/style.css">
{% endblock %}

{% block title %}  
<title>Add Recipe | Fresh House</title>
{% endblock %}

{% block content %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body class="container-grocery">
{% load cloudinary %}
<form method="POST" enctype="multipart/form-data">
<div class="text-center">
<div class="card" style="margin-top: 50px">
    <div class="text-left">
        {% csrf_token %}
        {{form.as_p}}
    </div>
</div>
</div>
<div class="text-center">
    <a href={%url 'recipes:recipes'%} class="btn btn-danger">Cancel</a>
    <input type="submit" class="btn btn-success" value="Add Recipe">
    <p></p>
</div>
</form>
</body>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% block head %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="/static/css/img/mylogo.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> -->

    {% block static %}
    {% endblock %}

    {% block title %}
    <title>Fresh House</title>
    {% endblock %}
</head>
{% endblock %}

<body>
    <section id="nav-bar">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="{% url 'main:home'%}"><img src="/static/css/img/mylogo.png" alt=""></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown active">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" data-target="navbarDropdown" role="button"
                             aria-haspopup="true" aria-expanded="false">
                            Home
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'main:home'%}">Home</a>
                            <a class="dropdown-item" href="{% url 'main:home'%}#about">About</a>
                            <a class="dropdown-item" href="{% url 'main:home'%}#contact-us">Contact</a>
                        </div>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'recipes:recipes' %}">Recipe <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'grocery'%}">Grocery <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'fastfood'%}">Fast Food <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'cart'%}">Cart <span class="sr-only">(current)</span></a>
                    </li>

                </ul>
            </div>
        </nav>
    </section>
    {% block content %} {% endblock %}



    <!-- FOOTER -->
    <section id="footer">
        <div style="text-align: center;">
            <p> &#xA9; 2020 Fresh House </p>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>


</html>

templates/cart.html
{% extends 'base.html' %}
{%load static%}

{% block head %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="icon" href="/static/css/img/mylogo.png" type="image/icon type">

    <title>Cart | Fresh House</title>
    <style>
        body {
        background: #F4F9F4;
        /* background: -webkit-linear-gradient(to right, #eecda3, #ef629f);
        background: linear-gradient(to right, #eecda3, #ef629f); */
        min-height: 100vh;
        }
        .rounded-fix {
            border-radius: 10px;
        }
        .bg-green {
            background-color: #A7D7C5;
        }
        .text-black {
            color: black;
        }
        .bg-darkgreen {
            background-color: #5C8D89;
        }
        .text-white {
            color: white;
        }
        .textstyle {
    background-color: #5C8D89; 
    font-weight: bold; /* Making font bold */
    border-radius: 20px; /* Making border radius */
    width: auto; /* Making auto-sizable width */
    height: auto; /* Making auto-sizable height */
    padding: 5px 30px 5px 30px; /* Making space around letters */
    font-size: 18px; /* Changing font size */
    border-width: 25px;
}
    </style>
{% block static %}
<link rel="stylesheet" href="/static/css/style.css">
{% endblock %}
</head>
{% endblock %}

{% block content %}
<body>
    <div class="px-4 px-lg-0">
        <!-- For demo purpose -->
        <div class="container text-black py-5 text-center">
          <h2 class="display-5" style="font-weight: bold;">This is Your Order Details</h2>
          <p class="lead mb-0">Don't forget to checkout and we will proceed immediately! &#128521;</p>
          </p>
        </div>
        <!-- End -->
      
        <div class="pb-5">
          <div class="container">
            <div class="row">
              <div class="col-lg-12 p-5 bg-green rounded-fix shadow-sm mb-5">
      
                <!-- Shopping cart table -->
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col" class="border-0 bg-light">
                          <div class="p-2 px-3 text-uppercase" style="text-align: center;">Product</div>
                        </th>
                        <th scope="col" class="border-0 bg-light">
                          <div class="py-2 text-uppercase" style="text-align: center;">Price</div>
                        </th>
                        <th scope="col" class="border-0 bg-light">
                          <div class="py-2 text-uppercase" style="text-align: center;">Quantity</div>
                        </th>
                        <!-- <th scope="col" class="border-0 bg-light">
                          <div class="py-2 text-uppercase">Remove</div>
                        </th> -->
                      </tr>
                    </thead>
                    <tbody>

                      <tr>
                        <th scope="row" class="border-0">
                          <div class="p-2">
                            <img src={{desc.foto.url}} style="width:100px;height:80px"; class="card-img-top" alt="photo not uploaded">
                            <div class="ml-3 d-inline-block align-middle">
                              <h5 class="mb-0"> <a href="#" class="text-dark d-inline-block align-middle">{{desc.nama}}</a></h5>
                              <span class="text-muted font-weight-normal font-italic d-block">{{desc.class_name}}</span>
                            </div>
                          </div>
                        </th>
                        <td class="border-0 align-middle" style="text-align: center;"><strong>{{desc.harga}}</strong></td>
                        <td class="border-0 align-middle" style="text-align: center;"><strong>{{desc.porsi}} </strong></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <!-- End -->
              </div>
            </div>
      
            <div class="py-5 p-4 bg-green rounded-fix shadow-sm" >
                
                <div class="p-4" style="width: 550px; margin: auto;">
                    <div class="textstyle text-white" style="text-align: center; font-size: 25px; margin-bottom: 20px; margin-top: -20px;">
                        Order summary </div>
                  <p class="font-italic mb-4" style="text-align: center;">Shipping and additional costs are calculated based on values you have entered.</p>
                  <ul class="list-unstyled mb-4">
                    <!-- <li class="d-flex justify-content-between py-3 border-bottom"><strong  style="color: black;">Order Subtotal </strong><strong>115.000</strong></li>
                    <li class="d-flex justify-content-between py-3 border-bottom"><strong style="color: black;">Shipping and handling</strong><strong>10.000</strong></li>
                    <li class="d-flex justify-content-between py-3 border-bottom"><strong style="color: black;">Tax (10%)</strong><strong>11.500</strong></li> -->
                    <li class="d-flex justify-content-between py-3 border-bottom"><strong style="color: black;">Total</strong>
                      <h5 class="font-weight-bold">Rp{{desc.harga}}</h5>
                    </li>
                  </ul><a href="{% url 'main:home'%}" class="btn btn-dark rounded-pill py-2 btn-block">Checkout and Pay</a>
                </div>
              
            </div>
      
          </div>
        </div>
      </div>
</body>
{% endblock %}

templates/fastfood.html
{% extends 'base.html' %}
{%load static%}

{% block static %}
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block title %}  
<title>Fast Food | Fresh House</title>
{% endblock %}

{% block content %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
<style> 
  form{
    padding-top: 30px;
    padding-right: 40px;
    padding-bottom: 30px;
    padding-left: 40px;
  }
</style>
</head>
<body class="container-fastfood">

<div class="search_engine">
  <form class="form-inline" action="{%url 'search' %}" method="POST" margin-left="100px">
    {% csrf_token %}
    <input type="text" class="form-control"  name="carinama" placeholder="What are you craving?" aria-label="Cari Produk">
    <button class="btn btn-outline-primary" type="submit" style="background-color:#5C8D89;"><i class="fa fa-search"></i></button>
</form>
</div>

  {% for res in result %}
  <div class="card" style="width: 18rem;">
      <div class="card-body">
        <img src="{{res.foto.url}}" class="card-img-top" alt="photo not uploaded">
        <h5 class="card-title">{{res.nama}}</h5>
        <p>Porsi per sajian : {{res.porsi}} </p>
        <p>Lokasi Toko : {{res.location}} </p>
        <h5>Rp {{res.harga}} </h5>
        <a href="cart/{{res.id}}/" class="btn btn-success">Add to Cart</a>
      </div>
    </div>
{% endfor %}

    
</body>


{% endblock content %}

templates/grocery.html
{% extends 'base.html' %}
{%load static%}

{% block static %}
    <link rel="stylesheet" href="/static/css/style.css">
{% endblock %}

{% block title %}  
<title>Grocery | Fresh House</title>
{% endblock %}

{% block content %}
<body class="container-fastfood">
  {% for res in result %}
  <div class="card" style="width: 18rem;">
      <div class="card-body">
        <img src="{{res.foto.url}}" class="card-img-top" alt="photo not uploaded">
        <h5 class="card-title">{{res.nama}}</h5>
        <p>Porsi per sajian : {{res.porsi}} </p>
        <p>Lokasi Toko : {{res.location}} </p>
        <h5>Rp {{res.harga}} </h5>
        <a href="cart/{{res.id}}/" class="btn btn-success">Add to Cart</a>
      </div>
    </div>
{% endfor %}

    
</body>


{% endblock content %}